### ISSUE TITLE
home vs about pages

### ISSUE THREAD

**Issue by mzelinka** [PCMDI/pcmdi.github.io#459]
Hi folks,

My two cents, but do we really need a page of very dense text on the Home page, and yet another page of very dense text on the "About-Overview" page?  The latter seems to contain mostly redundant but slightly out-of-date information vs the former, and could probably just go away. Alternatively, could all that text on the home page be sent to the About-Overview page, such that the home page is just a landing spot? 

@klein21 @durack1 @pochedls

**Comment by klein21** [comment]
Hi Mark,

In Issue #451 (https://github.com/PCMDI/pcmdi.github.io/issues/451#issuecomment-1077884424), I have already proposed deleting the “Overview” page due to its redundancy with the content on the home page, and it also being out of date.  Issue #451 awaiting resolution.   (I had been hoping that someone would enact the proposed changes).

But I do like your suggestion that we could move the content on the home page to the Overview page.    I now favor that, as that would have a minimal amount of needed changes to the overall organization of the website.

@durack1 @mzelinka @pochedls @mauzey1

**Comment by mzelinka** [comment]
I've made a [pull request](https://github.com/PCMDI/pcmdi.github.io/pull/460) to implement these changes

**Comment by pochedls** [comment]
@mzelinka - thanks. I definitely support this change – I think "less is more" in this case.

**Comment by mzelinka** [comment]
closing this, as these changes have been made
